[package]
authors = ["Jan Hohenheim <jan@hohenheim.ch>"]
edition = "2021"
name = "bevy_game"
publish = false
version = "0.1.0"

[features]
default = [   
    "bevy/bevy_winit",
    "bevy/render",
    "bevy/png",
    "bevy/x11",
    "bevy_kira_audio/ogg",
]

editor = [
    "dep:bevy_editor_pls",
]

dynamic = [
    "bevy/dynamic",
]

[dependencies]
bevy = { version = "0.9", default-features = false }
bevy_kira_audio = "0.13"
bevy_asset_loader = { version = "0.14", features = ["3d"] }
smooth-bevy-cameras = "0.6.0"

[dependencies.bevy_editor_pls]
git = "https://github.com/jakobhellermann/bevy_editor_pls"
rev = "e6d9bf8a919ca6c4a0bfa6207f368e66278a4e8f"
optional = true

[dependencies.bevy_rapier3d]
version = "0.19.0"
features = [
    "debug-render",
    "simd-nightly",
    "parallel",
]

[target."cfg(target_os = \"linux\")".dependencies]
winit = { version = "0.27", features = [ "x11" ]}


[target.'cfg(target_arch = "wasm32")'.dependencies]


[build-dependencies]
embed-resource = "1.4"

